### ISSUE TITLE
梅林固件如何删除脚本

### ISSUE THREAD

**Issue by SuperNG6** [zwmscorm/sharealiddns#3]
不停报错，准备重装，不知道卸载掉命令，能否提示一下
我尝试这条命令是不可以的
`sh /jffs/myscripts/sharealiddns/etc/init.d/sharealiddns.sh 
uninstall `
log
```
Jun  3 23:26:32 watchdog: start ddns.
Jun  3 23:26:32 rc_service: watchdog 978:notify_rc start_ddns
Jun  3 23:26:32 start_ddns: Error ddns server name: CUSTOM
```

**Comment by SuperNG6** [comment]
找到了

**Comment by zwmscorm** [comment]
cd /tmp/ && wget --no-check-certificate https://raw.githubusercontent.com/zwmscorm/sharealiddns/master/myscripts/sharealiddns-install.sh -O /tmp/sharealiddns-install.sh && sh /tmp/sharealiddns-install.sh
运行上上指令，希望输入uninstall
